### ISSUE TITLE
How can I show live NFT art using this module

### ISSUE THREAD

**Issue by Dreamfullstacker** [ArtBlocks/node-artblocks#10]
Hello everyone
I'm using this module with React.js to get token info and show live NFT art on webpage.
I got token info by this module but don't know how to show live NFT art on webpage based on the info.
How can I handle this problem?

**Comment by sheIby** [comment]
One way is to use in `iFrame` since the generator returns raw html.

```js
function Frame({html, width, height}) {
  return (
    <div>
      <iframe srcdoc={html} width={width} height={height} frameBorder="0"/>
    </div>
  )
}

let artblocks = new ArtBlocks("thegraph", "mainnet")

<Frame html={artblocks.token_generator(1234)} width={1000} height={1000}/>
```

**Comment by Dreamfullstacker** [comment]
![image](https://user-images.githubusercontent.com/97073529/187720528-ed7db07c-bec4-489f-8698-953f15d185ea.png)
I got this one

**Comment by Dreamfullstacker** [comment]
Hello @sheIby 
Thank you for your reply
I have solved the problem by your support
I read all project from Art block and get token info from them.
And show live NFT by script.
But as you know, running of script have some delay time and I want to show all tokens thumbnail to users
So user can see a preview of each NFT before they select NFT and see correct live NFT
How can I do this?

**Comment by sheIby** [comment]
Unfortunately that is outside of the scope of this repository, which is just to construct the generator scripts.
